### ISSUE TITLE
setState is not a function?

### ISSUE THREAD

**Issue by girvo** [jesseskinner/hoverboard#14]
Hey there,

![Example](https://i.imgur.com/u0Wcmur.png)

I attempted to run the example in the `README`, with Hoverboard loaded through WebPack and placed in the `window` context. As you can see, it doesn't seem to work. I'm running Hoverboard 1.5.0, which seems to be the latest?

Any ideas what's going on here?

Cheers

**Comment by jesseskinner** [comment]
Hey @girvo, sorry about the confusion. The problem is that the master README corresponds with 2.0 which hasn't been released yet. I plan to release it very soon. In the meantime, you can either use the version in the master branch, or refer to the README from 1.5:

https://github.com/jesseskinner/hoverboard/tree/v1.5.0

**Comment by jesseskinner** [comment]
@girvo Just wanted to let you know, v2 has now been released, with a much simpler API. Check it out, let me know if you have any questions or problems.
